# Generated by Django 4.0.4 on 2022-04-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('speciality', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Pediatrician', 'Pediatrician'), ('Radiologist', 'Radiologist')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('problem', models.TextField()),
                ('physician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='office_app.physician')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='office_app.physician')),
            ],
        ),
    ]
